# Generated by Django 3.0.6 on 2020-05-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprices',
            old_name='stock_id',
            new_name='ticker',
        ),
    ]
