# Generated by Django 3.0.6 on 2020-07-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200515_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('stock_name', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalprices',
            name='ticker',
        ),
        migrations.AddField(
            model_name='historicalprices',
            name='stock_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.StockInfo'),
        ),
    ]
