# Generated by Django 3.0.6 on 2020-07-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200718_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprices',
            name='stock_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockInfo'),
        ),
    ]
