# Generated by Django 3.0.6 on 2020-07-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200718_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='sector',
            field=models.CharField(max_length=30, verbose_name='行業別'),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='stock_name',
            field=models.CharField(max_length=20, verbose_name='股票名稱'),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='ticker',
            field=models.CharField(max_length=10, verbose_name='股票代號'),
        ),
    ]
