# Generated by Django 3.0.6 on 2020-07-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20200720_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprices',
            name='close',
            field=models.FloatField(verbose_name='收盤價'),
        ),
        migrations.AlterField(
            model_name='historicalprices',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='historicalprices',
            name='high',
            field=models.FloatField(verbose_name='(當日)最高價'),
        ),
        migrations.AlterField(
            model_name='historicalprices',
            name='low',
            field=models.FloatField(verbose_name='(當日)最低價'),
        ),
        migrations.AlterField(
            model_name='historicalprices',
            name='open',
            field=models.FloatField(verbose_name='開盤價'),
        ),
        migrations.AlterField(
            model_name='historicalprices',
            name='volume',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='交易量'),
        ),
    ]
