# Generated by Django 3.0.6 on 2020-09-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20200720_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.CharField(max_length=15, verbose_name='排行種類')),
                ('ranking_number', models.DecimalField(blank=True, decimal_places=0, max_digits=3, verbose_name='名次')),
                ('stock_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockInfo')),
            ],
        ),
    ]
