# Generated by Django 3.0.6 on 2020-09-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stockrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='last_modified',
            field=models.DateField(null=True, verbose_name='紀錄日期'),
        ),
    ]
