# Generated by Django 3.0.6 on 2020-09-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stockrecord_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockrecord',
            old_name='ranking_type',
            new_name='record_type',
        ),
    ]
